/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tp.client

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands
import tp.client.time.TimeCommand
import tp.client.time.show.ShowCommand

class TpCommand : CliktCommand() {

    override fun run() {
    }

}

fun main(args: Array<String>) =
    TpCommand()
        .subcommands(
            TimeCommand()
                .subcommands(
                    ShowCommand()
                )
        )
        .main(args)
